apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-prod
  template:
    metadata:
      labels:
        app: order-prod
    spec:
      containers:
      - name: order-prod
        image: amaan00101/order-prod:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: order-prod-service
spec:
  type: NodePort
  selector:
    app: order-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003